### ISSUE TITLE
Create: Springiness of pounded yam

### ISSUE THREAD

**Issue by dcornet** [Planteome/CO_343-yam-traits#28]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | CORNET    |
| **Program** | Cirad |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Springiness of pounded yam    |
| **Definition**         | Measurement of springiness based on Texture Profile Analysis using double compression test on pounded yam sample.     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Texture Profile Analysis using double compression test allwo to define springiness as the ratio between distances from the onset to peak force of the second to the first compression cycle.        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | proportion          |

**Comment by nmenda** [comment]
add new variable under 
https://yambase.org/cvterm/76710/view

**Comment by dcornet** [comment]
Hi, springiness (CO_343:0000446) and cohesiveness (CO_343:0000445) of pounded yam are both countinuous variables. But they appear as qualitative scoring in Yambase. Please could you modify this back to initial definition (i.e. measurment).

**Comment by nmenda** [comment]
@dcornet 
we will add new variables with a quantitative scale
