### ISSUE TITLE
Create: Cohesiveness of pounded yam

### ISSUE THREAD

**Issue by dcornet** [Planteome/CO_343-yam-traits#29]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | CORNET    |
| **Program** | Cirad |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Cohesiveness of pounded yam    |
| **Definition**         | Measurement of cohesiveness based on Texture Profile Analysis using double compression test on pounded yam sample.     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Texture Profile Analysis using double compression test allwo to define cohesiveness as the area underneath the second compression curve divided by the area underneath the first compression curve        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | proportion          |

**Comment by nmenda** [comment]
add new variable under 
https://yambase.org/cvterm/76860/view
