### ISSUE TITLE
Create: L

### ISSUE THREAD

**Issue by Adenikemi001** [Planteome/CO_343-yam-traits#33]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Alice Olatunji    |
| **Program** | international institute of tropical agriculture |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | L    |
| **Proposed Synonyms**  | L*     |
| **Definition**         | L indicates lightness which represents quantitative relationship of colors on three axes     |
| **Trait Class**        | Quality   |
| **Measurement Method** | colour reading using chromameter machine        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   |           |

**Comment by nmenda** [comment]
@Adenikemi001 should this trait request remain open?

**Comment by nmenda** [comment]
new variable of https://yambase.org/cvterm/78289/view
