### ISSUE TITLE
Create: a

### ISSUE THREAD

**Issue by Adenikemi001** [Planteome/CO_343-yam-traits#34]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Alice Olatunji    |
| **Program** | international institute of tropical agriculture |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | a    |
| **Proposed Synonyms**  | a*     |
| **Definition**         | a is a chromaticity coordinates     |
| **Trait Class**        | Quality   |
| **Measurement Method** | measured with chromameter machine        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   |           |

**Comment by nmenda** [comment]
https://yambase.org/cvterm/78289/view

**Comment by nmenda** [comment]
https://github.com/Planteome/CO_343-yam-traits/pull/50
