### ISSUE TITLE
Create: b

### ISSUE THREAD

**Issue by Adenikemi001** [Planteome/CO_343-yam-traits#35]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Alice Olatunji    |
| **Program** | international institute of tropical agriculture |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | b    |
| **Proposed Synonyms**  | b*     |
| **Definition**         | b* is a chromaticity coordinates     |
| **Trait Class**        | Quality   |
| **Measurement Method** | measured using chromameter machine        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   |           |

**Comment by nmenda** [comment]
add new L, A, and B quality traits without specifying a plant part. Can use later for post-composing in yambase

**Comment by nmenda** [comment]
https://yambase.org/cvterm/78289/view

**Comment by nmenda** [comment]
https://github.com/Planteome/CO_343-yam-traits/pull/50
