### ISSUE TITLE
Create: Area under disease progression curve

### ISSUE THREAD

**Issue by Adenikemi001** [Planteome/CO_343-yam-traits#36]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Alice Olatunji    |
| **Program** | international institute of tropical agriculture |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Area under disease progression curve    |
| **Proposed Synonyms**  | AUDPC_YMV     |
| **Definition**         | Area under disease progression curve for yam mosaic virus     |
| **Trait Class**        | Biotic Stress   |
| **Measurement Method** | calculated from the virus severity disease score at the various time intervals        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   |           |

**Comment by nmenda** [comment]
derives from https://yambase.org/cvterm/76763/view ?

**Comment by nmenda** [comment]
@Adenikemi001 
Need the formula for AUDPC for adding the new 'area' trait.
Will post compose the new trait with the time terms in yambase
