### ISSUE TITLE
Create: Area under disease progression curve

### ISSUE THREAD

**Issue by Adenikemi001** [Planteome/CO_343-yam-traits#37]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Alice Olatunji    |
| **Program** | international institute of tropical agriculture |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Area under disease progression curve    |
| **Proposed Synonyms**  | AUDPC_YAD     |
| **Definition**         | Area under disease progression curve for yam anthracnose disease     |
| **Trait Class**        | Biotic Stress   |
| **Measurement Method** | calculated from the yam severity anthracnose disease score at the time intervals        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   |           |

**Comment by nmenda** [comment]
@Adenikemi001 can you provide more info how the area is measured? Is it sq cm? and what are the time intervals for the measurements?

**Comment by nmenda** [comment]
derived from https://yambase.org/cvterm/76654/view ?

**Comment by nmenda** [comment]
Need the formula for AUDPC for creating a new trait 'AUDPC = area under disease progression curve' 

For the time points for measuring we will post compose the new trait with the month terms

**Comment by nmenda** [comment]
from @Adenikemi001: 
AUDPC  has no unit
The time interval is 30 days from 60DAP

Need to follow up for the formula
