### ISSUE TITLE
Create: Peak time 

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#42]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Peak time    |
| **Definition**         | The value of peak viscosity can explain the water-holding capacity of the starch or mixture     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Trait mesure in mesure in minute        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **Minimum** | Data recorded in minute    |
| **Maximum** | Data recorded in minute    |

**Comment by nmenda** [comment]
measured in number of minutes
