### ISSUE TITLE
Create: Aroma of boiled tuber

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#43]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Aroma of boiled tuber    |
| **Definition**         | Aroma mesure using the scale of 1-5 
Where (1-5 scale): 1= Dislike extremely; 2=Dislike; 3=Neither like nor dislike; 4=Like; 5=Like extremely     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Visual        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **1= Dislike extremely** | Dislike extremely    |
| **2=Dislike** | Dislike    |
| **3=Neither like nor dislike** | 3=Neither like nor dislike    |
| **4=Like** | 4=Like    |
| **5=Like extremely** | 5=Like extremely    |

**Comment by nmenda** [comment]
add a parent category 'tuber aroma'
