### ISSUE TITLE
Create: Appearance of boiled yam 

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#44]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Appearance of boiled yam    |
| **Definition**         | The appearance of the boiled yam is evaluated by a group of individuals using a scale of 1 - 5 Where (1-5 scale): 1= Dislike extremely; 2=Dislike; 3=Neither like nor dislike; 4=Like; 5=Like extremely.     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Visual rating        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **1= Dislike extremely** | 1= Dislike extremely    |
| **2=Dislike** | 2=Dislike    |
| **3=Neither like nor dislike** | 3=Neither like nor dislike    |
| **4=Like** | 4=Like    |
| **5=Like extremely** | 5=Like extremely    |

**Comment by nmenda** [comment]
add parent term under the 'quality' traits branch named 'tuber appearance quality' to differentiate from morphological 'tuber appearance'
