### ISSUE TITLE
Create: tuber flesh oxidation mesure @ 0, 30, 60, 180 minutes

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#45]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | tuber flesh oxidation mesure @ 0 minute    |
| **Definition**         | The tuber flesh oxidation is visually assessed using a scale of 0-3 where 0= no oxidization, 1= slightly oxidizing, and 3= highly oxidizing     |
| **Trait Class**        | Quality   |
| **Measurement Method** | visual        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **0= no oxidization** | 0= no oxidization    |
| **1= slightly oxidizing** | 1= slightly oxidizing    |
| **3= highly oxidizing** | 3= highly oxidizing    |

**Comment by nmenda** [comment]
create terms for 0,30,60,180 minutes under https://yambase.org/cvterm/76843/view

**Comment by nmenda** [comment]
CO_343:0003032
CO_343:0003033
CO_343:0003034
CO_343:0003035
