### ISSUE TITLE
Create: Yam boiled taste

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#46]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Yam boiled taste    |
| **Definition**         | The taste of boiled yam without any additional complementary food is scored using sensory test panelist with a scale of 1-5 where 1= very bitter, 2= Slightly bitter, 3= Neutral, 4= sweet and 5= very sweet     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Taste assessmet        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **1= very bitter** | 1= very bitter    |
| **2= Slightly bitter** | 2= Slightly bitter    |
| **3= Neutral** | 3= Neutral    |
| **4= sweet** | 4= sweet    |
| **5= very sweet** | 5= very sweet    |

**Comment by nmenda** [comment]
CO_343:0003030
