### ISSUE TITLE
Create: Yam tuber boiled colour

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#47]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Yam tuber boiled colour    |
| **Definition**         | the colour of the boiled yam is evaluated by a group of an individual using where (1-5 scale): 1= Dislike extremely; 2=Dislike; 3=Neither like nor dislike; 4=Like; 5=Like extremely     |
| **Trait Class**        | Quality   |
| **Measurement Method** | visual        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **1= Dislike extremely** | 1= Dislike extremely    |
| **2=Dislike** | 2=Dislike    |
| **3=Neither like nor dislike** | 3=Neither like nor dislike    |
| **4=Like;** | 4=Like    |
| **5=Like extremely** | 5=Like extremely    |

**Comment by nmenda** [comment]
new ID CO_343:0003028
