### ISSUE TITLE
Create: Texture of the tam tuber boiled 

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#48]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Texture of the tam tuber boiled    |
| **Definition**         | The texture of the boiled tuber is evaluated by a panel of individuals using (1-3 scale): Texture 1= strong; 2= intermediate; 3= soft     |
| **Trait Class**        | Quality   |
| **Measurement Method** | visual        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **1= strong** | 1= strong    |
| **2= intermediate** | 2= intermediate    |
| **3= soft** | 3= soft    |

**Comment by nmenda** [comment]
is this for raw yam? https://yambase.org/cvterm/76898/view

**Comment by nmenda** [comment]
new ID for boiled tuber  CO_343:00003027
