### ISSUE TITLE
Create: Mealiness of boiled tuber 

### ISSUE THREAD

**Issue by pa279** [Planteome/CO_343-yam-traits#49]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Paterne AGRE    |
| **Program** | International Institute of Tropical Agriculture (IITA) |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Mealiness of boiled tuber    |
| **Definition**         | The Mealiness of the boiled tuber is evaluated by a group of an individual using a (1 - 3 scale) as 1=soggy, 2= slightly mealy, 3= mealy     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Visual        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **1=soggy** | 1=soggy    |
| **2= slightly mealy** | 2= slightly mealy    |
| **3= mealy** | 3= mealy    |

**Comment by nmenda** [comment]
https://github.com/Planteome/CO_343-yam-traits/commit/9c337f32688ea6f107d5e4a4a679ec1be56e5233
